-- ~/.config/nvim/lua/configs/my_mappings.lua

local map = vim.keymap.set

-- Replace specific Georgian letters with English
local modes = { "n", "v", "x", "s", "o", "c" }

for _, mode in ipairs(modes) do
  --
  map(mode, "ჩ", "q", { noremap = true, silent = false })
  map(mode, "პ", "w", { noremap = true, silent = false })
  map(mode, "უ", "e", { noremap = true, silent = false })
  map(mode, "ძ", "r", { noremap = true, silent = false })
  map(mode, "ჭ", "t", { noremap = true, silent = false })
  map(mode, "ტ", "y", { noremap = true, silent = false })
  map(mode, "თ", "u", { noremap = true, silent = false })
  map(mode, "ნ", "i", { noremap = true, silent = false })
  map(mode, "ვ", "o", { noremap = true, silent = false })
  map(mode, "შ", "p", { noremap = true, silent = false })
  map(mode, "კ", "[", { noremap = true, silent = false })
  map(mode, "ქ", "]", { noremap = true, silent = false })
  --
  map(mode, "ხ", "a", { noremap = true, silent = false })
  map(mode, "ი", "s", { noremap = true, silent = false })
  map(mode, "ა", "d", { noremap = true, silent = false })
  map(mode, "ე", "f", { noremap = true, silent = false })
  map(mode, "ო", "g", { noremap = true, silent = false })
  map(mode, "დ", "h", { noremap = true, silent = false })
  map(mode, "მ", "j", { noremap = true, silent = false })
  map(mode, "ს", "k", { noremap = true, silent = false })
  map(mode, "რ", "l", { noremap = true, silent = false })
  map(mode, "ბ", ";", { noremap = true, silent = false })
  map(mode, "გ", "'", { noremap = true, silent = false })

  map(mode, "ჯ", "z", { noremap = true, silent = false })
  map(mode, "ჰ", "x", { noremap = true, silent = false })
  map(mode, "ყ", "c", { noremap = true, silent = false })
  map(mode, "ღ", "v", { noremap = true, silent = false })
  map(mode, "ჟ", "b", { noremap = true, silent = false })
  map(mode, "ზ", "n", { noremap = true, silent = false })
  map(mode, "ც", "m", { noremap = true, silent = false })
  map(mode, "ლ", ",", { noremap = true })
  map(mode, "ფ", ".", { noremap = true, silent = false })
  map(mode, "წ", "/", { noremap = true, silent = false })
  --
  map(mode, "Ჩ", "Q", { noremap = true, silent = false })
  map(mode, "Პ", "W", { noremap = true, silent = false })
  map(mode, "Უ", "E", { noremap = true, silent = false })
  map(mode, "Ძ", "R", { noremap = true, silent = false })
  map(mode, "Ჭ", "T", { noremap = true, silent = false })
  map(mode, "Ტ", "Y", { noremap = true, silent = false })
  map(mode, "Თ", "U", { noremap = true, silent = false })
  map(mode, "Ნ", "I", { noremap = true, silent = false })
  map(mode, "Ვ", "O", { noremap = true, silent = false })
  map(mode, "Შ", "P", { noremap = true, silent = false })
  map(mode, "Კ", "{", { noremap = true, silent = false })
  map(mode, "Ქ", "}", { noremap = true, silent = false })
  --
  map(mode, "Ხ", "A", { noremap = true, silent = false })
  map(mode, "Ი", "S", { noremap = true, silent = false })
  map(mode, "Ა", "D", { noremap = true, silent = false })
  map(mode, "Ე", "F", { noremap = true, silent = false })
  map(mode, "Ო", "G", { noremap = true, silent = false })
  map(mode, "Დ", "H", { noremap = true, silent = false })
  map(mode, "Მ", "J", { noremap = true, silent = false })
  map(mode, "Ს", "K", { noremap = true, silent = false })
  map(mode, "Რ", "L", { noremap = true, silent = false })
  map(mode, "Ბ", ":", { noremap = true, silent = false })
  map(mode, "Გ", '"', { noremap = true, silent = false })
  --
  map(mode, "Ჯ", "Z", { noremap = true, silent = false })
  map(mode, "Ჰ", "X", { noremap = true, silent = false })
  map(mode, "Ყ", "C", { noremap = true, silent = false })
  map(mode, "Ღ", "V", { noremap = true, silent = false })
  map(mode, "Ჟ", "G", { noremap = true, silent = false })
  map(mode, "Ზ", "N", { noremap = true, silent = false })
  map(mode, "Ც", "M", { noremap = true, silent = false })
  map(mode, "Ლ", "<", { noremap = true, silent = false })
  map(mode, "Ფ", ">", { noremap = true, silent = false })
  map(mode, "Წ", "?", { noremap = true, silent = false })
  --
  --
  map(mode, "й", "q", { noremap = true, silent = false })
  map(mode, "ц", "w", { noremap = true, silent = false })
  map(mode, "у", "e", { noremap = true, silent = false })
  map(mode, "к", "r", { noremap = true, silent = false })
  map(mode, "е", "t", { noremap = true, silent = false })
  map(mode, "н", "y", { noremap = true, silent = false })
  map(mode, "г", "u", { noremap = true, silent = false })
  map(mode, "ш", "i", { noremap = true, silent = false })
  map(mode, "щ", "o", { noremap = true, silent = false })
  map(mode, "з", "p", { noremap = true, silent = false })
  map(mode, "х", "[", { noremap = true, silent = false })
  map(mode, "ъ", "]", { noremap = true, silent = false })
  --
  map(mode, "ф", "a", { noremap = true, silent = false })
  map(mode, "ы", "s", { noremap = true, silent = false })
  map(mode, "в", "d", { noremap = true, silent = false })
  map(mode, "а", "f", { noremap = true, silent = false })
  map(mode, "п", "g", { noremap = true, silent = false })
  map(mode, "р", "h", { noremap = true, silent = false })
  map(mode, "о", "j", { noremap = true, silent = false })
  map(mode, "л", "k", { noremap = true, silent = false })
  map(mode, "д", "l", { noremap = true, silent = false })
  map(mode, "ж", ";", { noremap = true, silent = false })
  map(mode, "э", "'", { noremap = true, silent = false })

  map(mode, "я", "z", { noremap = true, silent = false })
  map(mode, "ч", "x", { noremap = true, silent = false })
  map(mode, "с", "c", { noremap = true, silent = false })
  map(mode, "м", "v", { noremap = true, silent = false })
  map(mode, "и", "b", { noremap = true, silent = false })
  map(mode, "т", "n", { noremap = true, silent = false })
  map(mode, "ь", "m", { noremap = true, silent = false })
  map(mode, "б", ",", { noremap = true })
  map(mode, "ю", ".", { noremap = true, silent = false })
  map(mode, ".", "/", { noremap = true, silent = false })
  --
  map(mode, "Й", "Q", { noremap = true, silent = false })
  map(mode, "Ц", "W", { noremap = true, silent = false })
  map(mode, "У", "E", { noremap = true, silent = false })
  map(mode, "К", "R", { noremap = true, silent = false })
  map(mode, "Е", "T", { noremap = true, silent = false })
  map(mode, "Н", "Y", { noremap = true, silent = false })
  map(mode, "Г", "U", { noremap = true, silent = false })
  map(mode, "Ш", "I", { noremap = true, silent = false })
  map(mode, "Щ", "O", { noremap = true, silent = false })
  map(mode, "З", "P", { noremap = true, silent = false })
  map(mode, "Х", "{", { noremap = true, silent = false })
  map(mode, "Ъ", "}", { noremap = true, silent = false })
  --
  map(mode, "Ф", "A", { noremap = true, silent = false })
  map(mode, "Ы", "S", { noremap = true, silent = false })
  map(mode, "В", "D", { noremap = true, silent = false })
  map(mode, "А", "F", { noremap = true, silent = false })
  map(mode, "П", "G", { noremap = true, silent = false })
  map(mode, "Р", "H", { noremap = true, silent = false })
  map(mode, "О", "J", { noremap = true, silent = false })
  map(mode, "Л", "K", { noremap = true, silent = false })
  map(mode, "Д", "L", { noremap = true, silent = false })
  map(mode, "Ж", ":", { noremap = true, silent = false })
  map(mode, "Э", '"', { noremap = true, silent = false })
  --
  map(mode, "Я", "Z", { noremap = true, silent = false })
  map(mode, "Ч", "X", { noremap = true, silent = false })
  map(mode, "С", "C", { noremap = true, silent = false })
  map(mode, "М", "V", { noremap = true, silent = false })
  map(mode, "И", "G", { noremap = true, silent = false })
  map(mode, "Т", "N", { noremap = true, silent = false })
  map(mode, "Ь", "M", { noremap = true, silent = false })
  map(mode, "Б", "<", { noremap = true, silent = false })
  map(mode, "Ю", ">", { noremap = true, silent = false })
  map(mode, ",", "?", { noremap = true, silent = false })
  --
  -- დაამატეთ მეტი ასო საჭიროებისამებრ
  -- map(mode, 'ქ', 'q', { noremap = true, silent = true, desc = "Replace ქ with q" })
end
